language: android
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.0
    - android-28
    - extra-google-m2repository
    - extra-android-m2repository
jdk:
    - oraclejdk8
licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
before_script:
    - chmod +x gradlew
